//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run.StorageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageServiceReference.IStorageService")]
    public interface IStorageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetSum", ReplyAction="http://tempuri.org/IStorageService/GetSumResponse")]
        int GetSum(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetSum", ReplyAction="http://tempuri.org/IStorageService/GetSumResponse")]
        System.Threading.Tasks.Task<int> GetSumAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetWeatherFromDbByCity", ReplyAction="http://tempuri.org/IStorageService/GetWeatherFromDbByCityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpenWeatherMap.CurrentWeatherResponse))]
        OpenWeatherMap.WeatherItem GetWeatherFromDbByCity(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetWeatherFromDbByCity", ReplyAction="http://tempuri.org/IStorageService/GetWeatherFromDbByCityResponse")]
        System.Threading.Tasks.Task<OpenWeatherMap.WeatherItem> GetWeatherFromDbByCityAsync(string cityName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorageServiceChannel : Run.StorageServiceReference.IStorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<Run.StorageServiceReference.IStorageService>, Run.StorageServiceReference.IStorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSum(int x, int y) {
            return base.Channel.GetSum(x, y);
        }
        
        public System.Threading.Tasks.Task<int> GetSumAsync(int x, int y) {
            return base.Channel.GetSumAsync(x, y);
        }
        
        public OpenWeatherMap.WeatherItem GetWeatherFromDbByCity(string cityName) {
            return base.Channel.GetWeatherFromDbByCity(cityName);
        }
        
        public System.Threading.Tasks.Task<OpenWeatherMap.WeatherItem> GetWeatherFromDbByCityAsync(string cityName) {
            return base.Channel.GetWeatherFromDbByCityAsync(cityName);
        }
    }
}
